// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: buget.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listBuget = `-- name: ListBuget :many
SELECT buget_financial_data_id, subject_code, budget, result, difference, category_id, buget_fiscal_year
FROM t_buget_financial_data
ORDER BY buget_financial_data_id
`

func (q *Queries) ListBuget(ctx context.Context) ([]TBugetFinancialDatum, error) {
	rows, err := q.db.Query(ctx, listBuget)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TBugetFinancialDatum
	for rows.Next() {
		var i TBugetFinancialDatum
		if err := rows.Scan(
			&i.BugetFinancialDataID,
			&i.SubjectCode,
			&i.Budget,
			&i.Result,
			&i.Difference,
			&i.CategoryID,
			&i.BugetFiscalYear,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveBuget = `-- name: SaveBuget :exec
INSERT INTO t_buget_financial_data
(subject_code, budget, result, difference, category_id, buget_fiscal_year)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (subject_code, category_id, buget_fiscal_year) DO UPDATE 
SET subject_code = EXCLUDED.subject_code,
    budget = EXCLUDED.budget,
    result = EXCLUDED.result,
    difference = EXCLUDED.difference,
    category_id = EXCLUDED.category_id,
    buget_fiscal_year = EXCLUDED.buget_fiscal_year
`

type SaveBugetParams struct {
	SubjectCode     int16          `json:"subject_code"`
	Budget          pgtype.Numeric `json:"budget"`
	Result          pgtype.Numeric `json:"result"`
	Difference      pgtype.Numeric `json:"difference"`
	CategoryID      int16          `json:"category_id"`
	BugetFiscalYear int16          `json:"buget_fiscal_year"`
}

func (q *Queries) SaveBuget(ctx context.Context, arg SaveBugetParams) error {
	_, err := q.db.Exec(ctx, saveBuget,
		arg.SubjectCode,
		arg.Budget,
		arg.Result,
		arg.Difference,
		arg.CategoryID,
		arg.BugetFiscalYear,
	)
	return err
}
