// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cashbook.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listCashbook = `-- name: ListCashbook :many
SELECT cashbook_id, cashbook_date, item, withdrawal, deposit, balance, remarks, book_code, book_year
FROM t_cashbook
ORDER BY cashbook_id
`

func (q *Queries) ListCashbook(ctx context.Context) ([]TCashbook, error) {
	rows, err := q.db.Query(ctx, listCashbook)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TCashbook
	for rows.Next() {
		var i TCashbook
		if err := rows.Scan(
			&i.CashbookID,
			&i.CashbookDate,
			&i.Item,
			&i.Withdrawal,
			&i.Deposit,
			&i.Balance,
			&i.Remarks,
			&i.BookCode,
			&i.BookYear,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveCashbook = `-- name: SaveCashbook :exec
INSERT INTO t_cashbook
(cashbook_date, item, withdrawal, deposit, balance, remarks, book_code, book_year)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (book_code, book_year) DO UPDATE 
SET cashbook_date = EXCLUDED.cashbook_date,
    item = EXCLUDED.item,
    withdrawal = EXCLUDED.withdrawal,
    deposit = EXCLUDED.deposit,
    balance = EXCLUDED.balance,
    remarks = EXCLUDED.remarks,
    book_code = EXCLUDED.book_code,
    book_year = EXCLUDED.book_year
`

type SaveCashbookParams struct {
	CashbookDate pgtype.Date    `json:"cashbook_date"`
	Item         pgtype.Text    `json:"item"`
	Withdrawal   pgtype.Numeric `json:"withdrawal"`
	Deposit      pgtype.Numeric `json:"deposit"`
	Balance      pgtype.Numeric `json:"balance"`
	Remarks      pgtype.Text    `json:"remarks"`
	BookCode     int16          `json:"book_code"`
	BookYear     int16          `json:"book_year"`
}

func (q *Queries) SaveCashbook(ctx context.Context, arg SaveCashbookParams) error {
	_, err := q.db.Exec(ctx, saveCashbook,
		arg.CashbookDate,
		arg.Item,
		arg.Withdrawal,
		arg.Deposit,
		arg.Balance,
		arg.Remarks,
		arg.BookCode,
		arg.BookYear,
	)
	return err
}
