// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: category.sql

package dbgen

import (
	"context"
)

const listCategories = `-- name: ListCategories :many
SELECT category_id, category_name
FROM m_categories
ORDER BY category_id
`

func (q *Queries) ListCategories(ctx context.Context) ([]MCategory, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MCategory
	for rows.Next() {
		var i MCategory
		if err := rows.Scan(&i.CategoryID, &i.CategoryName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveCategory = `-- name: SaveCategory :exec
INSERT INTO m_categories (category_name)
VALUES ($1)
ON CONFLICT DO NOTHING
`

func (q *Queries) SaveCategory(ctx context.Context, categoryName string) error {
	_, err := q.db.Exec(ctx, saveCategory, categoryName)
	return err
}
