// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: journal.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listJournal = `-- name: ListJournal :many
SELECT journal_id, journal_date, withdrawal, deposit, subject_code, item, customer, evidence, memo, book_code, category_id, fiscal_year
FROM t_journal
ORDER BY journal_id
`

func (q *Queries) ListJournal(ctx context.Context) ([]TJournal, error) {
	rows, err := q.db.Query(ctx, listJournal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TJournal
	for rows.Next() {
		var i TJournal
		if err := rows.Scan(
			&i.JournalID,
			&i.JournalDate,
			&i.Withdrawal,
			&i.Deposit,
			&i.SubjectCode,
			&i.Item,
			&i.Customer,
			&i.Evidence,
			&i.Memo,
			&i.BookCode,
			&i.CategoryID,
			&i.FiscalYear,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveJournal = `-- name: SaveJournal :exec
INSERT INTO t_journal
(journal_date, withdrawal, deposit, subject_code, item, customer, evidence, memo, book_code, category_id, fiscal_year)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type SaveJournalParams struct {
	JournalDate pgtype.Date    `json:"journal_date"`
	Withdrawal  pgtype.Numeric `json:"withdrawal"`
	Deposit     pgtype.Numeric `json:"deposit"`
	SubjectCode int16          `json:"subject_code"`
	Item        pgtype.Text    `json:"item"`
	Customer    string         `json:"customer"`
	Evidence    pgtype.Text    `json:"evidence"`
	Memo        pgtype.Text    `json:"memo"`
	BookCode    int16          `json:"book_code"`
	CategoryID  int16          `json:"category_id"`
	FiscalYear  int16          `json:"fiscal_year"`
}

func (q *Queries) SaveJournal(ctx context.Context, arg SaveJournalParams) error {
	_, err := q.db.Exec(ctx, saveJournal,
		arg.JournalDate,
		arg.Withdrawal,
		arg.Deposit,
		arg.SubjectCode,
		arg.Item,
		arg.Customer,
		arg.Evidence,
		arg.Memo,
		arg.BookCode,
		arg.CategoryID,
		arg.FiscalYear,
	)
	return err
}
