// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type MBook struct {
	BookCode int16  `json:"book_code"`
	BookName string `json:"book_name"`
}

type MCategory struct {
	CategoryID   int16  `json:"category_id"`
	CategoryName string `json:"category_name"`
}

type MSubject struct {
	SubjectCode int16  `json:"subject_code"`
	SubjectName string `json:"subject_name"`
}

type TBugetFinancialDatum struct {
	BugetFinancialDataID int32          `json:"buget_financial_data_id"`
	SubjectCode          int16          `json:"subject_code"`
	Budget               pgtype.Numeric `json:"budget"`
	Result               pgtype.Numeric `json:"result"`
	Difference           pgtype.Numeric `json:"difference"`
	CategoryID           int16          `json:"category_id"`
	BugetFiscalYear      int16          `json:"buget_fiscal_year"`
}

type TCashbook struct {
	CashbookID   int32          `json:"cashbook_id"`
	CashbookDate pgtype.Date    `json:"cashbook_date"`
	Item         pgtype.Text    `json:"item"`
	Withdrawal   pgtype.Numeric `json:"withdrawal"`
	Deposit      pgtype.Numeric `json:"deposit"`
	Balance      pgtype.Numeric `json:"balance"`
	Remarks      pgtype.Text    `json:"remarks"`
	BookCode     int16          `json:"book_code"`
	BookYear     int16          `json:"book_year"`
}

type TJournal struct {
	JournalID   int32          `json:"journal_id"`
	JournalDate pgtype.Date    `json:"journal_date"`
	Withdrawal  pgtype.Numeric `json:"withdrawal"`
	Deposit     pgtype.Numeric `json:"deposit"`
	SubjectCode int16          `json:"subject_code"`
	Item        pgtype.Text    `json:"item"`
	Customer    string         `json:"customer"`
	Evidence    pgtype.Text    `json:"evidence"`
	Memo        pgtype.Text    `json:"memo"`
	BookCode    int16          `json:"book_code"`
	CategoryID  int16          `json:"category_id"`
	FiscalYear  int16          `json:"fiscal_year"`
}

type TPayable struct {
	PayableID   int32          `json:"payable_id"`
	PayableDate pgtype.Date    `json:"payable_date"`
	Withdrawal  pgtype.Numeric `json:"withdrawal"`
	Deposit     pgtype.Numeric `json:"deposit"`
	SubjectCode int16          `json:"subject_code"`
	Item        pgtype.Text    `json:"item"`
	Customer    string         `json:"customer"`
	Evidence    pgtype.Text    `json:"evidence"`
	Memo        pgtype.Text    `json:"memo"`
	BookCode    int16          `json:"book_code"`
	CategoryID  int16          `json:"category_id"`
	FiscalYear  int16          `json:"fiscal_year"`
}

type TReceivable struct {
	ReceivableID   int32          `json:"receivable_id"`
	ReceivableDate pgtype.Date    `json:"receivable_date"`
	Withdrawal     pgtype.Numeric `json:"withdrawal"`
	Deposit        pgtype.Numeric `json:"deposit"`
	SubjectCode    int16          `json:"subject_code"`
	Item           pgtype.Text    `json:"item"`
	Customer       string         `json:"customer"`
	Evidence       pgtype.Text    `json:"evidence"`
	Memo           pgtype.Text    `json:"memo"`
	BookCode       int16          `json:"book_code"`
	CategoryID     int16          `json:"category_id"`
	FiscalYear     int16          `json:"fiscal_year"`
}
