// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: book.sql

package dbgen

import (
	"context"
)

const listBooks = `-- name: ListBooks :many
SELECT book_code, book_name 
FROM m_books 
ORDER BY book_code
`

func (q *Queries) ListBooks(ctx context.Context) ([]MBook, error) {
	rows, err := q.db.Query(ctx, listBooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MBook
	for rows.Next() {
		var i MBook
		if err := rows.Scan(&i.BookCode, &i.BookName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveBook = `-- name: SaveBook :exec
INSERT INTO m_books (book_code, book_name)
VALUES ($1, $2)
ON CONFLICT (book_code) DO UPDATE 
SET book_name = EXCLUDED.book_name
`

type SaveBookParams struct {
	BookCode int16  `json:"book_code"`
	BookName string `json:"book_name"`
}

func (q *Queries) SaveBook(ctx context.Context, arg SaveBookParams) error {
	_, err := q.db.Exec(ctx, saveBook, arg.BookCode, arg.BookName)
	return err
}
