// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subject.sql

package dbgen

import (
	"context"
)

const listSubjects = `-- name: ListSubjects :many
SELECT subject_code, subject_name 
FROM m_subjects 
ORDER BY subject_code
`

func (q *Queries) ListSubjects(ctx context.Context) ([]MSubject, error) {
	rows, err := q.db.Query(ctx, listSubjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MSubject
	for rows.Next() {
		var i MSubject
		if err := rows.Scan(&i.SubjectCode, &i.SubjectName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveSubject = `-- name: SaveSubject :exec
INSERT INTO m_subjects (subject_code, subject_name)
VALUES ($1, $2)
ON CONFLICT (subject_code) DO UPDATE 
SET subject_name = EXCLUDED.subject_name
`

type SaveSubjectParams struct {
	SubjectCode int16  `json:"subject_code"`
	SubjectName string `json:"subject_name"`
}

func (q *Queries) SaveSubject(ctx context.Context, arg SaveSubjectParams) error {
	_, err := q.db.Exec(ctx, saveSubject, arg.SubjectCode, arg.SubjectName)
	return err
}
